TRANSLATE_CODE_STAGE4_PROMPT = """
あなたは、優秀な翻訳家です。与えられる数学、コード、科学に関するテキストを、正確かつ自然な日本語に以下のガイドラインに従って翻訳してください。

ガイドライン:
1. 専門用語の正確性: 数学、コード、科学に関する専門用語は無理に日本語に訳す必要はありません。単語のみ英語表記で構いません。
2. 数式の保持: 数式はそのままの形式で保持してください。数式内の変数や関数名も変更しないでください。
3. コードの保持: プログラミングコードはそのままの形式で保持してください。コード内の変数名、関数名は変更しないでください。コメントも無理のない範囲で翻訳してください。
4. 文体とトーン: 学術的な文体を維持し、できるだけ自然な日本語に翻訳してください。
5. 網羅性: 元のテキストをすべて翻訳してください。特に条件、制約など、根幹に関わる部分を省略しないでください。

Example:
-----Original Text-----:
During a normal walk in the forest, Katie has stumbled upon a mysterious code! However, the mysterious code had some characters unreadable. She has written down this code as a string $$$c$$$ consisting of lowercase English characters and asterisks (\"*\"), where each of the asterisks denotes an unreadable character. Excited with her discovery, Katie has decided to recover the unreadable characters by replacing each asterisk with arbitrary lowercase English letter (different asterisks might be replaced with different letters).\n\nKatie has a favorite string $$$s$$$ and a not-so-favorite string $$$t$$$ and she would love to recover the mysterious code so that it has as many occurrences of $$$s$$$ as possible and as little occurrences of $$$t$$$ as possible. Formally, let's denote $$$f(x, y)$$$ as the number of occurrences of $$$y$$$ in $$$x$$$ (for example, $$$f(aababa, ab) = 2$$$). Katie wants to recover the code $$$c'$$$ conforming to the original $$$c$$$, such that $$$f(c', s) - f(c', t)$$$ is largest possible. However, Katie is not very good at recovering codes in general, so she would like you to help her out.\n\nInput\n\nThe first line contains string $$$c$$$ ($$$1 \\leq |c| \\leq 1000$$$) — the mysterious code . It is guaranteed that $$$c$$$ consists of lowercase English characters and asterisks \"*\" only.\n\nThe second and third line contain strings $$$s$$$ and $$$t$$$ respectively ($$$1 \\leq |s|, |t| \\leq 50$$$, $$$s \\neq t$$$). It is guaranteed that $$$s$$$ and $$$t$$$ consist of lowercase English characters only.\n\nOutput\n\nPrint a single integer — the largest possible value of $$$f(c', s) - f(c', t)$$$ of the recovered code.\n\nExamples\n\nInput\n\n*****\nkatie\nshiro\n\nOutput\n\n1\n\nInput\n\ncaat\ncaat\na\n\nOutput\n\n-1\n\nInput\n\n*a*\nbba\nb\n\nOutput\n\n0\n\nInput\n\n***\ncc\nz\n\nOutput\n\n2\n\nNote\n\nIn the first example, for $$$c'$$$ equal to \"katie\" $$$f(c', s) = 1$$$ and $$$f(c', t) = 0$$$, which makes $$$f(c', s) - f(c', t) = 1$$$ which is the largest possible.\n\nIn the second example, the only $$$c'$$$ conforming to the given $$$c$$$ is \"caat\". The corresponding $$$f(c', s) - f(c', t) = 1 - 2 = -1$$$.\n\nIn the third example, there are multiple ways to recover the code such that $$$f(c', s) - f(c', t)$$$ is largest possible, for example \"aaa\", \"aac\", or even \"zaz\". The value of $$$f(c', s) - f(c', t) = 0$$$ for all of these recovered codes.\n\nIn the fourth example, the optimal recovered code $$$c'$$$ would be \"ccc\". The corresponding $$$f(c', s) - f(c', t) = 2$$$.

-----Translated Text-----:
ケイティが森の中を普通に散歩していたとき、彼女は不思議な暗号を発見しました。しかし、この謎の暗号には一部解読できない文字が含まれていました。彼女はこの暗号を、小文字の英字とアスタリスク（`"*"`）で構成される文字列 $c$ として書き留めました。ここで各アスタリスクは解読不能な文字を表しています。発見に興奮したケイティは、各アスタリスクを任意の小文字の英字に置き換えることで、解読不能な文字を復元することにしました。\n\nケイティにはお気に入りの文字列 $s$ と、それほど好きではない文字列 $t$ があり、謎の暗号を復元する際に、$s$ が可能な限り多く出現し、$t$ が可能な限り少なく出現するようにしたいと考えています。\n\n形式的には、$f(x, y)$ を文字列 $x$ 中における文字列 $y$ の出現回数と定義します（例えば、$f(aababa, ab) = 2$）。ケイティは、元の暗号 $c$ に準拠した復元暗号 $c'$ を見つけ、$f(c', s) - f(c', t)$ が可能な限り最大になるようにしたいと考えています。ただし、ケイティは一般的に暗号を復元するのがあまり得意ではないため、あなたの助けを必要としています。\n\nInput\n\n最初の行には文字列 $c$ が与えられます（$1 \\leq |c| \\leq 1000$）。これは謎の暗号です。$c$ は小文字の英字とアスタリスク `"*"` のみで構成されることが保証されています。\n\n2行目と3行目にはそれぞれ文字列 $s$ と $t$ が与えられます（$1 \\leq |s|, |t| \\leq 50$, $s \\neq t$）。\n\n$s$ と $t$ は小文字の英字のみで構成されることが保証されています。\n\nOutput\n\n復元された暗号 $c'$ について、$f(c', s) - f(c', t)$ の最大可能値を1つの整数として出力してください。\n\nExamples\n\nInput\n\n*****\nkatie\nshiro\n\nOutput\n\n1\n\nInput\n\ncaat\ncaat\na\n\nOutput\n\n-1\n\nInput\n\n*a*\nbba\nb\n\nOutput\n\n0\n\nInput\n\n***\ncc\nz\n\nOutput\n\n2\n\nNote\n\n最初の例では、$c'$ が "katie" の場合、$f(c', s) = 1$ かつ $f(c', t) = 0$ となり、$f(c', s) - f(c', t) = 1$ となります。これは可能な最大値です。\n\n2番目の例では、与えられた $c$ に準拠する唯一の $c'$ は "caat" です。対応する $f(c', s) - f(c', t) = 1 - 2 = -1$ となります。\n\n3番目の例では、$f(c', s) - f(c', t)$ が最大となる暗号を復元する方法が複数存在します。例えば "aaa"、"aac"、あるいは "zaz" などです。これらすべての復元された暗号において、$f(c', s) - f(c', t) = 0$ となります。\n\n4番目の例では、最適な復元暗号 $c'$ は "ccc" となります。対応する $f(c', s) - f(c', t) = 2$ となります。

--- End of Prompt
決して問題を解いてはいけません。
あなたが出力するべきは、次に与えられるテキストを日本語に翻訳したものだけです。
"""
